#!/usr/bin/env bash

#//******************************//#
#//# Author: by uriid1          #//#
#//# license: GNU GPL           #//#
#//# telegram: @rp_party        #//#
#//# Mail: appdurov@gmail.com   #//#
####****************************####

# Run
clear
cd tg-py-love
python3 main.py $1 $2
